version: "3.9"
services:
  master-node:
    image: "${IMAGE}"
    container_name: "master"
    cap_add:
      - SYS_RESOURCE
    ports:
      - "12000:12000"
      - "9443:9443"
      - "8443:8443"
      - "6379:6379"
      - "6372:6378"
    environment:
      - RE_USERNAME=${RE_USERNAME}
      - RE_PASS=${RE_PASS}
      - RE_CLUSTER_NAME=${RE_CLUSTER_NAME}
      - RE_DB_PORT=${RE_DB_PORT}
      - RE_USE_OSS_CLUSTER=${RE_USE_OSS_CLUSTER}
    volumes:
      - "$PWD/setup_cluster.sh:/opt/setup_cluster.sh"
      - "$PWD/create_db.sh:/opt/create_db.sh"
    networks:
      cluster:
        ipv4_address: 172.28.5.2

  node-1:
    image: "${IMAGE}"
    container_name: "slave-1"
    cap_add:
      - SYS_RESOURCE
    depends_on:
      - master-node
    ports:
      - "12001:12000"
      - "9444:9443"
      - "8444:8443"
      - "6373:6378"
    environment:
      - RE_USERNAME=${RE_USERNAME}
      - RE_PASS=${RE_PASS}
      - RE_CLUSTER_NAME=${RE_CLUSTER_NAME}
      - RE_DB_PORT=${RE_DB_PORT}
      - RE_USE_OSS_CLUSTER=${RE_USE_OSS_CLUSTER}
    volumes:
      - "$PWD/join_node.sh:/opt/join_node.sh"
    networks:
      cluster:
        ipv4_address: 172.28.5.3

  node-2:
    image: "${IMAGE}"
    container_name: "slave-2"
    cap_add:
      - SYS_RESOURCE
    depends_on:
      - node-1
    ports:
      - "12002:12000"
      - "9445:9443"
      - "8445:8443"
      - "6374:6378"
    environment:
      - RE_USERNAME=${RE_USERNAME}
      - RE_PASS=${RE_PASS}
      - RE_CLUSTER_NAME=${RE_CLUSTER_NAME}
      - RE_DB_PORT=${RE_DB_PORT}
      - RE_USE_OSS_CLUSTER=${RE_USE_OSS_CLUSTER}
    volumes:
      - "$PWD/join_node.sh:/opt/join_node.sh"
    networks:
      cluster:
        ipv4_address: 172.28.5.4

networks:
  cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254