name: Tests

on:
  push:
    branches:
      - main
      - '[0-9].[0-9]'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build_cluster:
    name: Redis EE (${{ matrix.type }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        type:
          - proxy
          - oss-cluster

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build cluster
        env:
          IMAGE: redislabs/redis:latest
          RE_USERNAME: test@test.com
          RE_PASS: 12345
          RE_CLUSTER_NAME: test
          OSS_CLUSTER: ${{ matrix.type == 'oss-cluster' && true || false }}
          DB_PORT: ${{ matrix.type == 'oss-cluster' && 6378 || 6379 }}
        run: | 
          ./build.sh
          sleep 5

      - name: Run PING command
        env:
          DB_PORT: ${{ matrix.type == 'oss-cluster' && 6378 || 6379 }}
        run: |
          docker-compose exec -T master-node bash -c "/opt/redislabs/bin/redis-cli -p ${{ env.DB_PORT }} ping"